// ============================================================
//  Premier League 26/27 – Spillere for autocomplete
//  Oppdatert 19. august 2026 – alle 20 klubber gjennomgått (vinduet stenger 1. sept)
//  Listen er et utgangspunkt – deltakere kan også skrive fritt.
// ============================================================

const PLAYERS = [
  // Arsenal
  { name:'Bukayo Saka', team:'ARS', pos:'Kant' },
  { name:'Martin Ødegaard', team:'ARS', pos:'Midtbane' },
  { name:'Viktor Gyökeres', team:'ARS', pos:'Spiss' },
  { name:'Eberechi Eze', team:'ARS', pos:'Midtbane' },
  { name:'Kai Havertz', team:'ARS', pos:'Spiss' },
  { name:'Gabriel Martinelli', team:'ARS', pos:'Kant' },
  { name:'Declan Rice', team:'ARS', pos:'Midtbane' },
  { name:'Ethan Nwaneri', team:'ARS', pos:'Midtbane' },
  { name:'Christos Tzolis', team:'ARS', pos:'Kant' },
  { name:'Piero Hincapié', team:'ARS', pos:'Forsvar' },
  { name:'Bruno Guimarães', team:'ARS', pos:'Midtbane' },
  { name:'Fabio Vieira', team:'ARS', pos:'Midtbane' },
  { name:'William Saliba', team:'ARS', pos:'Forsvar' },
  { name:'Gabriel Magalhães', team:'ARS', pos:'Forsvar' },
  { name:'Jurriën Timber', team:'ARS', pos:'Forsvar' },
  { name:'Riccardo Calafiori', team:'ARS', pos:'Forsvar' },
  { name:'Myles Lewis-Skelly', team:'ARS', pos:'Forsvar' },
  { name:'Ben White', team:'ARS', pos:'Forsvar' },
  { name:'Martín Zubimendi', team:'ARS', pos:'Midtbane' },
  { name:'Mikel Merino', team:'ARS', pos:'Midtbane' },
  { name:'Leandro Trossard', team:'ARS', pos:'Kant' },
  { name:'Noni Madueke', team:'ARS', pos:'Kant' },
  { name:'Max Dowman', team:'ARS', pos:'Kant' },
  // Aston Villa
  { name:'Ollie Watkins', team:'AVL', pos:'Spiss' },
  { name:'Evann Guessand', team:'AVL', pos:'Spiss' },
  { name:'Johan Manzambi', team:'AVL', pos:'Midtbane' },
  { name:'John McGinn', team:'AVL', pos:'Midtbane' },
  { name:'Leon Bailey', team:'AVL', pos:'Kant' },
  { name:'João Gomes', team:'AVL', pos:'Midtbane' },
  { name:'Alejandro Garnacho', team:'AVL', pos:'Kant' },
  { name:'Modou Kéba Cissé', team:'AVL', pos:'Forsvar' },
  { name:'Harvey Elliott', team:'AVL', pos:'Midtbane' },
  { name:'Emiliano Buendía', team:'AVL', pos:'Midtbane' },
  { name:'Boubacar Kamara', team:'AVL', pos:'Midtbane' },
  { name:'Amadou Onana', team:'AVL', pos:'Midtbane' },
  { name:'Donyell Malen', team:'AVL', pos:'Kant' },
  { name:'Jadon Sancho', team:'AVL', pos:'Kant' },
  { name:'Ezri Konsa', team:'AVL', pos:'Forsvar' },
  { name:'Pau Torres', team:'AVL', pos:'Forsvar' },
  { name:'Matty Cash', team:'AVL', pos:'Forsvar' },
  { name:'Ian Maatsen', team:'AVL', pos:'Forsvar' },
  { name:'Lucas Digne', team:'AVL', pos:'Forsvar' },
  { name:'Tyrone Mings', team:'AVL', pos:'Forsvar' },
  // Bournemouth
  { name:'Antoine Semenyo', team:'BOU', pos:'Kant' },
  { name:'Evanilson', team:'BOU', pos:'Spiss' },
  { name:'Justin Kluivert', team:'BOU', pos:'Midtbane' },
  { name:'Álvaro Rodríguez', team:'BOU', pos:'Spiss' },
  { name:'Antonio Silva', team:'BOU', pos:'Forsvar' },
  { name:'Juanlu Sánchez', team:'BOU', pos:'Forsvar' },
  { name:'Marcus Tavernier', team:'BOU', pos:'Kant' },
  { name:'Ryan Christie', team:'BOU', pos:'Midtbane' },
  { name:'Lewis Cook', team:'BOU', pos:'Midtbane' },
  { name:'Alex Scott', team:'BOU', pos:'Midtbane' },
  { name:'Ben Doak', team:'BOU', pos:'Kant' },
  { name:'David Brooks', team:'BOU', pos:'Kant' },
  { name:'Bafodé Diakité', team:'BOU', pos:'Forsvar' },
  { name:'Adam Smith', team:'BOU', pos:'Forsvar' },
  { name:'Julián Araujo', team:'BOU', pos:'Forsvar' },
  { name:'Amine Adli', team:'BOU', pos:'Kant' },
  { name:'Eli Junior Kroupi', team:'BOU', pos:'Spiss' },
  // Brentford
  { name:'Igor Thiago', team:'BRE', pos:'Spiss' },
  { name:'Yoane Wissa', team:'BRE', pos:'Spiss' },
  { name:'Kevin Schade', team:'BRE', pos:'Kant' },
  { name:'Jaidon Anthony', team:'BRE', pos:'Kant' },
  { name:'Callum Wilson', team:'BRE', pos:'Spiss' },
  { name:'Mamadou Sangaré', team:'BRE', pos:'Midtbane' },
  { name:'Jannik Schuster', team:'BRE', pos:'Forsvar' },
  { name:'Mikkel Damsgaard', team:'BRE', pos:'Midtbane' },
  { name:'Vitaly Janelt', team:'BRE', pos:'Midtbane' },
  { name:'Yehor Yarmoliuk', team:'BRE', pos:'Midtbane' },
  { name:'Fábio Carvalho', team:'BRE', pos:'Midtbane' },
  { name:'Keane Lewis-Potter', team:'BRE', pos:'Kant' },
  { name:'Nathan Collins', team:'BRE', pos:'Forsvar' },
  { name:'Ethan Pinnock', team:'BRE', pos:'Forsvar' },
  { name:'Sepp van den Berg', team:'BRE', pos:'Forsvar' },
  { name:'Kristoffer Ajer', team:'BRE', pos:'Forsvar' },
  { name:'Michael Kayode', team:'BRE', pos:'Forsvar' },
  { name:'Dango Ouattara', team:'BRE', pos:'Kant' },
  // Brighton
  { name:'Kaoru Mitoma', team:'BHA', pos:'Kant' },
  { name:'Georginio Rutter', team:'BHA', pos:'Midtbane' },
  { name:'Evan Ferguson', team:'BHA', pos:'Spiss' },
  { name:'Zadok Yohanna', team:'BHA', pos:'Spiss' },
  { name:'Luka Vušković', team:'BHA', pos:'Forsvar' },
  { name:'Pascal Struijk', team:'BHA', pos:'Forsvar' },
  { name:'Jan Paul van Hecke', team:'BHA', pos:'Forsvar' },
  { name:'Costinha', team:'BHA', pos:'Forsvar' },
  { name:'Michael Svoboda', team:'BHA', pos:'Forsvar' },
  { name:'Rodrigo Rêgo', team:'BHA', pos:'Kant' },
  { name:'Yankuba Minteh', team:'BHA', pos:'Kant' },
  { name:'Carlos Baleba', team:'BHA', pos:'Midtbane' },
  { name:'Diego Gómez', team:'BHA', pos:'Midtbane' },
  { name:'Yasin Ayari', team:'BHA', pos:'Midtbane' },
  { name:'Mats Wieffer', team:'BHA', pos:'Midtbane' },
  { name:'Jack Hinshelwood', team:'BHA', pos:'Midtbane' },
  { name:'Brajan Gruda', team:'BHA', pos:'Kant' },
  { name:'Ferdi Kadıoğlu', team:'BHA', pos:'Forsvar' },
  { name:'Joel Veltman', team:'BHA', pos:'Forsvar' },
  { name:'Adam Webster', team:'BHA', pos:'Forsvar' },
  { name:'Maxim De Cuyper', team:'BHA', pos:'Forsvar' },
  // Chelsea
  { name:'Cole Palmer', team:'CHE', pos:'Midtbane' },
  { name:'João Pedro', team:'CHE', pos:'Spiss' },
  { name:'Morgan Rogers', team:'CHE', pos:'Midtbane' },
  { name:'Estêvão', team:'CHE', pos:'Kant' },
  { name:'Liam Delap', team:'CHE', pos:'Spiss' },
  { name:'Emmanuel Emegha', team:'CHE', pos:'Spiss' },
  { name:'Danny Welbeck', team:'CHE', pos:'Spiss' },
  { name:'Jordan Henderson', team:'CHE', pos:'Midtbane' },
  { name:'Mykhailo Mudryk', team:'CHE', pos:'Kant' },
  { name:'Geovany Quenda', team:'CHE', pos:'Kant' },
  { name:'Enzo Fernández', team:'CHE', pos:'Midtbane' },
  { name:'Moisés Caicedo', team:'CHE', pos:'Midtbane' },
  { name:'Pedro Neto', team:'CHE', pos:'Kant' },
  { name:'Maxence Lacroix', team:'CHE', pos:'Forsvar' },
  { name:'Valentín Barco', team:'CHE', pos:'Midtbane' },
  { name:'Marc Palestra', team:'CHE', pos:'Forsvar' },
  { name:'Pep Chavarría', team:'CHE', pos:'Forsvar' },
  { name:'Nicolas Jackson', team:'CHE', pos:'Spiss' },
  { name:'Reece James', team:'CHE', pos:'Forsvar' },
  { name:'Levi Colwill', team:'CHE', pos:'Forsvar' },
  { name:'Marc Cucurella', team:'CHE', pos:'Forsvar' },
  { name:'Malo Gusto', team:'CHE', pos:'Forsvar' },
  { name:'Trevoh Chalobah', team:'CHE', pos:'Forsvar' },
  { name:'Tosin Adarabioyo', team:'CHE', pos:'Forsvar' },
  { name:'Wesley Fofana', team:'CHE', pos:'Forsvar' },
  { name:'Josh Acheampong', team:'CHE', pos:'Forsvar' },
  { name:'Roméo Lavia', team:'CHE', pos:'Midtbane' },
  { name:'Dário Essugo', team:'CHE', pos:'Midtbane' },
  { name:'Jamie Gittens', team:'CHE', pos:'Kant' },
  // Coventry
  { name:'Haji Wright', team:'COV', pos:'Spiss' },
  { name:'Ellis Simms', team:'COV', pos:'Spiss' },
  { name:'Loum Tchaouna', team:'COV', pos:'Kant' },
  { name:'Frank Onyeka', team:'COV', pos:'Midtbane' },
  { name:'Gustavo Hamer', team:'COV', pos:'Midtbane' },
  { name:'Caleb Yirenkyi', team:'COV', pos:'Midtbane' },
  { name:'Aurèle Amenda', team:'COV', pos:'Forsvar' },
  { name:'Brandon Thomas-Asante', team:'COV', pos:'Spiss' },
  { name:'Jack Rudoni', team:'COV', pos:'Midtbane' },
  { name:'Josh Eccles', team:'COV', pos:'Midtbane' },
  { name:'Matt Grimes', team:'COV', pos:'Midtbane' },
  { name:'Tatsuhiro Sakamoto', team:'COV', pos:'Kant' },
  { name:'Bobby Thomas', team:'COV', pos:'Forsvar' },
  { name:'Liam Kitching', team:'COV', pos:'Forsvar' },
  { name:'Milan van Ewijk', team:'COV', pos:'Forsvar' },
  { name:'Jay Dasilva', team:'COV', pos:'Forsvar' },
  { name:'Victor Torp', team:'COV', pos:'Midtbane' },
  // Crystal Palace
  { name:'Anan Khalaili', team:'CRY', pos:'Kant' },
  { name:'Jean-Philippe Mateta', team:'CRY', pos:'Spiss' },
  { name:'Ismaïla Sarr', team:'CRY', pos:'Kant' },
  { name:'Adam Wharton', team:'CRY', pos:'Midtbane' },
  { name:'Matheus França', team:'CRY', pos:'Midtbane' },
  { name:'Dwight McNeil', team:'CRY', pos:'Kant' },
  { name:'Takehiro Tomiyasu', team:'CRY', pos:'Forsvar' },
  { name:'Oscar Mingueza', team:'CRY', pos:'Forsvar' },
  { name:'Daniel Muñoz', team:'CRY', pos:'Forsvar' },
  { name:'Tyrick Mitchell', team:'CRY', pos:'Forsvar' },
  { name:'Chris Richards', team:'CRY', pos:'Forsvar' },
  { name:'Borna Sosa', team:'CRY', pos:'Forsvar' },
  { name:'Jefferson Lerma', team:'CRY', pos:'Midtbane' },
  { name:'Will Hughes', team:'CRY', pos:'Midtbane' },
  { name:'Justin Devenny', team:'CRY', pos:'Midtbane' },
  { name:'Romain Esse', team:'CRY', pos:'Kant' },
  { name:'Yeremy Pino', team:'CRY', pos:'Kant' },
  { name:'Christantus Uche', team:'CRY', pos:'Spiss' },
  { name:'Daichi Kamada', team:'CRY', pos:'Midtbane' },
  // Everton
  { name:'Iliman Ndiaye', team:'EVE', pos:'Kant' },
  { name:'Jack Grealish', team:'EVE', pos:'Kant' },
  { name:'Beto', team:'EVE', pos:'Spiss' },
  { name:'Brennan Johnson', team:'EVE', pos:'Kant' },
  { name:'Merlin Röhl', team:'EVE', pos:'Midtbane' },
  { name:'Hayden Hackney', team:'EVE', pos:'Midtbane' },
  { name:'Tyrique George', team:'EVE', pos:'Kant' },
  { name:'Christian Nørgaard', team:'EVE', pos:'Midtbane' },
  { name:'Jarrad Branthwaite', team:'EVE', pos:'Forsvar' },
  { name:'James Tarkowski', team:'EVE', pos:'Forsvar' },
  { name:'Vitaliy Mykolenko', team:'EVE', pos:'Forsvar' },
  { name:'Michael Keane', team:'EVE', pos:'Forsvar' },
  { name:'Jake O\'Brien', team:'EVE', pos:'Forsvar' },
  { name:'Idrissa Gueye', team:'EVE', pos:'Midtbane' },
  { name:'James Garner', team:'EVE', pos:'Midtbane' },
  { name:'Carlos Alcaraz', team:'EVE', pos:'Midtbane' },
  { name:'Thierno Barry', team:'EVE', pos:'Spiss' },
  { name:'Nathan Patterson', team:'EVE', pos:'Forsvar' },
  // Fulham
  { name:'Rodrigo Muniz', team:'FUL', pos:'Spiss' },
  { name:'Alex Iwobi', team:'FUL', pos:'Midtbane' },
  { name:'Emile Smith Rowe', team:'FUL', pos:'Midtbane' },
  { name:'Jonah Kusi-Asare', team:'FUL', pos:'Spiss' },
  { name:'Gonzalo García', team:'FUL', pos:'Spiss' },
  { name:'Shea Charles', team:'FUL', pos:'Midtbane' },
  { name:'César Palacios', team:'FUL', pos:'Midtbane' },
  { name:'Raúl Jiménez', team:'FUL', pos:'Spiss' },
  { name:'Adama Traoré', team:'FUL', pos:'Kant' },
  { name:'Andreas Pereira', team:'FUL', pos:'Midtbane' },
  { name:'Tom Cairney', team:'FUL', pos:'Midtbane' },
  { name:'Sander Berge', team:'FUL', pos:'Midtbane' },
  { name:'Josh King', team:'FUL', pos:'Midtbane' },
  { name:'Antonee Robinson', team:'FUL', pos:'Forsvar' },
  { name:'Calvin Bassey', team:'FUL', pos:'Forsvar' },
  { name:'Joachim Andersen', team:'FUL', pos:'Forsvar' },
  { name:'Kenny Tete', team:'FUL', pos:'Forsvar' },
  { name:'Ryan Sessegnon', team:'FUL', pos:'Forsvar' },
  // Hull
  { name:'Lucas Gourna-Douath', team:'HUL', pos:'Midtbane' },
  { name:'Enis Destan', team:'HUL', pos:'Spiss' },
  { name:'Hidemasa Morita', team:'HUL', pos:'Midtbane' },
  { name:'Oscar Zambrano', team:'HUL', pos:'Midtbane' },
  { name:'Matt Targett', team:'HUL', pos:'Forsvar' },
  { name:'Joe Gelhardt', team:'HUL', pos:'Spiss' },
  { name:'Abu Kamara', team:'HUL', pos:'Kant' },
  { name:'Regan Slater', team:'HUL', pos:'Midtbane' },
  { name:'Ryan Giles', team:'HUL', pos:'Forsvar' },
  { name:'Lewie Coyle', team:'HUL', pos:'Forsvar' },
  { name:'Alfie Jones', team:'HUL', pos:'Forsvar' },
  { name:'Charlie Hughes', team:'HUL', pos:'Forsvar' },
  { name:'John Lundstram', team:'HUL', pos:'Midtbane' },
  { name:'Kasey Palmer', team:'HUL', pos:'Midtbane' },
  { name:'Mason Burstow', team:'HUL', pos:'Spiss' },
  // Ipswich
  { name:'Julio Enciso', team:'IPS', pos:'Kant' },
  { name:'Abdoul Ouattara', team:'IPS', pos:'Kant' },
  { name:'Emersonn', team:'IPS', pos:'Spiss' },
  { name:'Chuba Akpom', team:'IPS', pos:'Spiss' },
  { name:'Daizen Maeda', team:'IPS', pos:'Kant' },
  { name:'Abdul Fatawu', team:'IPS', pos:'Kant' },
  { name:'Omari Hutchinson', team:'IPS', pos:'Midtbane' },
  { name:'Sasa Lukić', team:'IPS', pos:'Midtbane' },
  { name:'Issa Diop', team:'IPS', pos:'Forsvar' },
  { name:'Florentino Luís', team:'IPS', pos:'Midtbane' },
  { name:'Jack Clarke', team:'IPS', pos:'Kant' },
  { name:'George Hirst', team:'IPS', pos:'Spiss' },
  { name:'Conor Chaplin', team:'IPS', pos:'Midtbane' },
  { name:'Jens Cajuste', team:'IPS', pos:'Midtbane' },
  { name:'Leif Davis', team:'IPS', pos:'Forsvar' },
  { name:'Dara O\'Shea', team:'IPS', pos:'Forsvar' },
  { name:'Ben Johnson', team:'IPS', pos:'Forsvar' },
  { name:'Cameron Burgess', team:'IPS', pos:'Forsvar' },
  { name:'Wes Burns', team:'IPS', pos:'Kant' },
  { name:'Jaden Philogene', team:'IPS', pos:'Kant' },
  // Leeds
  { name:'Joel Piroe', team:'LEE', pos:'Spiss' },
  { name:'Harry Wilson', team:'LEE', pos:'Kant' },
  { name:'Daniel James', team:'LEE', pos:'Kant' },
  { name:'Brenden Aaronson', team:'LEE', pos:'Midtbane' },
  { name:'Mateo Joseph', team:'LEE', pos:'Spiss' },
  { name:'Tarik Muharemović', team:'LEE', pos:'Forsvar' },
  { name:'Ao Tanaka', team:'LEE', pos:'Midtbane' },
  { name:'Ethan Ampadu', team:'LEE', pos:'Midtbane' },
  { name:'Anton Stach', team:'LEE', pos:'Midtbane' },
  { name:'Sean Longstaff', team:'LEE', pos:'Midtbane' },
  { name:'Willy Gnonto', team:'LEE', pos:'Kant' },
  { name:'Largie Ramazani', team:'LEE', pos:'Kant' },
  { name:'Noah Okafor', team:'LEE', pos:'Kant' },
  { name:'Lukas Nmecha', team:'LEE', pos:'Spiss' },
  { name:'Dominic Calvert-Lewin', team:'LEE', pos:'Spiss' },
  { name:'Jayden Bogle', team:'LEE', pos:'Forsvar' },
  { name:'Jaka Bijol', team:'LEE', pos:'Forsvar' },
  // Liverpool
  { name:'Alexander Isak', team:'LIV', pos:'Spiss' },
  { name:'Florian Wirtz', team:'LIV', pos:'Midtbane' },
  { name:'Hugo Ekitike', team:'LIV', pos:'Spiss' },
  { name:'Cody Gakpo', team:'LIV', pos:'Kant' },
  { name:'Dominik Szoboszlai', team:'LIV', pos:'Midtbane' },
  { name:'Víctor Muñoz', team:'LIV', pos:'Kant' },
  { name:'Jeremy Jacquet', team:'LIV', pos:'Forsvar' },
  { name:'Ronald Araújo', team:'LIV', pos:'Forsvar' },
  { name:'Virgil van Dijk', team:'LIV', pos:'Forsvar' },
  { name:'Ibrahima Konaté', team:'LIV', pos:'Forsvar' },
  { name:'Conor Bradley', team:'LIV', pos:'Forsvar' },
  { name:'Miloš Kerkez', team:'LIV', pos:'Forsvar' },
  { name:'Jeremie Frimpong', team:'LIV', pos:'Forsvar' },
  { name:'Joe Gomez', team:'LIV', pos:'Forsvar' },
  { name:'Ryan Gravenberch', team:'LIV', pos:'Midtbane' },
  { name:'Alexis Mac Allister', team:'LIV', pos:'Midtbane' },
  { name:'Curtis Jones', team:'LIV', pos:'Midtbane' },
  { name:'Wataru Endo', team:'LIV', pos:'Midtbane' },
  { name:'Rio Ngumoha', team:'LIV', pos:'Kant' },
  { name:'Federico Chiesa', team:'LIV', pos:'Kant' },
  // Man City
  { name:'Erling Haaland', team:'MCI', pos:'Spiss' },
  { name:'Phil Foden', team:'MCI', pos:'Midtbane' },
  { name:'Rayan Cherki', team:'MCI', pos:'Midtbane' },
  { name:'Omar Marmoush', team:'MCI', pos:'Spiss' },
  { name:'Jérémy Doku', team:'MCI', pos:'Kant' },
  { name:'Savinho', team:'MCI', pos:'Kant' },
  { name:'Elliot Anderson', team:'MCI', pos:'Midtbane' },
  { name:'Jeremy Monga', team:'MCI', pos:'Kant' },
  { name:'Bernardo Silva', team:'MCI', pos:'Midtbane' },
  { name:'Tijjani Reijnders', team:'MCI', pos:'Midtbane' },
  { name:'Nico González', team:'MCI', pos:'Midtbane' },
  { name:'Mateo Kovačić', team:'MCI', pos:'Midtbane' },
  { name:'Nico O\'Reilly', team:'MCI', pos:'Forsvar' },
  { name:'Rúben Dias', team:'MCI', pos:'Forsvar' },
  { name:'Joško Gvardiol', team:'MCI', pos:'Forsvar' },
  { name:'John Stones', team:'MCI', pos:'Forsvar' },
  { name:'Abdukodir Khusanov', team:'MCI', pos:'Forsvar' },
  { name:'Rico Lewis', team:'MCI', pos:'Forsvar' },
  { name:'Matheus Nunes', team:'MCI', pos:'Forsvar' },
  { name:'Oscar Bobb', team:'MCI', pos:'Kant' },
  // Man Utd
  { name:'Bryan Mbeumo', team:'MUN', pos:'Kant' },
  { name:'Matheus Cunha', team:'MUN', pos:'Spiss' },
  { name:'Benjamin Šeško', team:'MUN', pos:'Spiss' },
  { name:'Bruno Fernandes', team:'MUN', pos:'Midtbane' },
  { name:'Amad Diallo', team:'MUN', pos:'Kant' },
  { name:'Marcus Rashford', team:'MUN', pos:'Kant' },
  { name:'Youri Tielemans', team:'MUN', pos:'Midtbane' },
  { name:'Andrey Santos', team:'MUN', pos:'Midtbane' },
  { name:'Kobbie Mainoo', team:'MUN', pos:'Midtbane' },
  { name:'Manuel Ugarte', team:'MUN', pos:'Midtbane' },
  { name:'Mason Mount', team:'MUN', pos:'Midtbane' },
  { name:'Casemiro', team:'MUN', pos:'Midtbane' },
  { name:'Diogo Dalot', team:'MUN', pos:'Forsvar' },
  { name:'Luke Shaw', team:'MUN', pos:'Forsvar' },
  { name:'Leny Yoro', team:'MUN', pos:'Forsvar' },
  { name:'Matthijs de Ligt', team:'MUN', pos:'Forsvar' },
  { name:'Noussair Mazraoui', team:'MUN', pos:'Forsvar' },
  { name:'Patrick Dorgu', team:'MUN', pos:'Forsvar' },
  { name:'Ayden Heaven', team:'MUN', pos:'Forsvar' },
  { name:'Joshua Zirkzee', team:'MUN', pos:'Spiss' },
  // Newcastle
  { name:'Nick Woltemade', team:'NEW', pos:'Spiss' },
  { name:'Harvey Barnes', team:'NEW', pos:'Kant' },
  { name:'Jacob Murphy', team:'NEW', pos:'Kant' },
  { name:'Bazoumana Touré', team:'NEW', pos:'Kant' },
  { name:'Aladji Bamba', team:'NEW', pos:'Midtbane' },
  { name:'Sean Steur', team:'NEW', pos:'Midtbane' },
  { name:'Joelinton', team:'NEW', pos:'Midtbane' },
  { name:'Anthony Elanga', team:'NEW', pos:'Kant' },
  { name:'Jacob Ramsey', team:'NEW', pos:'Midtbane' },
  { name:'Joe Willock', team:'NEW', pos:'Midtbane' },
  { name:'Lewis Miley', team:'NEW', pos:'Midtbane' },
  { name:'William Osula', team:'NEW', pos:'Spiss' },
  { name:'Sven Botman', team:'NEW', pos:'Forsvar' },
  { name:'Dan Burn', team:'NEW', pos:'Forsvar' },
  { name:'Fabian Schär', team:'NEW', pos:'Forsvar' },
  { name:'Tino Livramento', team:'NEW', pos:'Forsvar' },
  { name:'Lewis Hall', team:'NEW', pos:'Forsvar' },
  { name:'Malick Thiaw', team:'NEW', pos:'Forsvar' },
  // Nottingham Forest
  { name:'Chris Wood', team:'NFO', pos:'Spiss' },
  { name:'Morgan Gibbs-White', team:'NFO', pos:'Midtbane' },
  { name:'Callum Hudson-Odoi', team:'NFO', pos:'Kant' },
  { name:'Arnaud Kalimuendo', team:'NFO', pos:'Spiss' },
  { name:'Xaver Schlager', team:'NFO', pos:'Midtbane' },
  { name:'Ousmane Diomande', team:'NFO', pos:'Forsvar' },
  { name:'Nikola Milenković', team:'NFO', pos:'Forsvar' },
  { name:'Murillo', team:'NFO', pos:'Forsvar' },
  { name:'Neco Williams', team:'NFO', pos:'Forsvar' },
  { name:'Ola Aina', team:'NFO', pos:'Forsvar' },
  { name:'Nicolò Savona', team:'NFO', pos:'Forsvar' },
  { name:'Ryan Yates', team:'NFO', pos:'Midtbane' },
  { name:'Ibrahim Sangaré', team:'NFO', pos:'Midtbane' },
  { name:'Douglas Luiz', team:'NFO', pos:'Midtbane' },
  { name:'James McAtee', team:'NFO', pos:'Midtbane' },
  { name:'Dan Ndoye', team:'NFO', pos:'Kant' },
  { name:'Igor Jesus', team:'NFO', pos:'Spiss' },
  // Sunderland
  { name:'Wilson Isidor', team:'SUN', pos:'Spiss' },
  { name:'Granit Xhaka', team:'SUN', pos:'Midtbane' },
  { name:'Simon Adingra', team:'SUN', pos:'Kant' },
  { name:'Enzo Le Fée', team:'SUN', pos:'Midtbane' },
  { name:'Thomas Meunier', team:'SUN', pos:'Forsvar' },
  { name:'Chemsdine Talbi', team:'SUN', pos:'Kant' },
  { name:'Bertrand Traoré', team:'SUN', pos:'Kant' },
  { name:'Habib Diarra', team:'SUN', pos:'Midtbane' },
  { name:'Noah Sadiki', team:'SUN', pos:'Midtbane' },
  { name:'Chris Rigg', team:'SUN', pos:'Midtbane' },
  { name:'Eliezer Mayenda', team:'SUN', pos:'Spiss' },
  { name:'Brian Brobbey', team:'SUN', pos:'Spiss' },
  { name:'Dan Ballard', team:'SUN', pos:'Forsvar' },
  { name:'Trai Hume', team:'SUN', pos:'Forsvar' },
  { name:'Dennis Cirkin', team:'SUN', pos:'Forsvar' },
  { name:'Nordi Mukiele', team:'SUN', pos:'Forsvar' },
  { name:'Reinildo', team:'SUN', pos:'Forsvar' },
  // Tottenham
  { name:'Dominic Solanke', team:'TOT', pos:'Spiss' },
  { name:'Xavi Simons', team:'TOT', pos:'Midtbane' },
  { name:'Mohammed Kudus', team:'TOT', pos:'Kant' },
  { name:'James Maddison', team:'TOT', pos:'Midtbane' },
  { name:'Mateus Fernandes', team:'TOT', pos:'Midtbane' },
  { name:'Sandro Tonali', team:'TOT', pos:'Midtbane' },
  { name:'Andy Robertson', team:'TOT', pos:'Forsvar' },
  { name:'Marcos Senesi', team:'TOT', pos:'Forsvar' },
  { name:'Richarlison', team:'TOT', pos:'Spiss' },
  { name:'Dejan Kulusevski', team:'TOT', pos:'Midtbane' },
  { name:'Pape Matar Sarr', team:'TOT', pos:'Midtbane' },
  { name:'Lucas Bergvall', team:'TOT', pos:'Midtbane' },
  { name:'Yves Bissouma', team:'TOT', pos:'Midtbane' },
  { name:'Archie Gray', team:'TOT', pos:'Midtbane' },
  { name:'Wilson Odobert', team:'TOT', pos:'Kant' },
  { name:'Micky van de Ven', team:'TOT', pos:'Forsvar' },
  { name:'Destiny Udogie', team:'TOT', pos:'Forsvar' },
  { name:'Pedro Porro', team:'TOT', pos:'Forsvar' },
  { name:'Kevin Danso', team:'TOT', pos:'Forsvar' },
];

// ── API-oppdatering ────────────────────────────────────────
// Admin kan hente fersk troppsdata fra football-data.org. Resultatet lagres i
// nettleserens localStorage og overstyrer listene under – ingen filer trenger
// å endres. (Overstyringen er per nettleser inntil appen får en felles backend.)
const PLAYERS_OVERRIDE_LS = 'pl2627_players_override';
function getOverride() { try { return JSON.parse(localStorage.getItem(PLAYERS_OVERRIDE_LS) || 'null'); } catch(e) { return null; } }
function setPlayersOverride(data) { localStorage.setItem(PLAYERS_OVERRIDE_LS, JSON.stringify(data)); }
function clearPlayersOverride() { localStorage.removeItem(PLAYERS_OVERRIDE_LS); }
function effectivePlayers() { const o = getOverride(); return (o && o.players && o.players.length) ? o.players : PLAYERS; }
function effectiveKeepers() { const o = getOverride(); return (o && o.keepers && o.keepers.length) ? o.keepers : KEEPERS; }

// Enkelt søk: matcher på navn (delstreng), rangerer treff som starter med søkeord først
function searchPlayers(q) {
  q = (q || '').trim().toLowerCase();
  const list = effectivePlayers();
  if (!q) return list.slice(0, 8);
  const starts = [], contains = [];
  list.forEach(p => {
    const n = p.name.toLowerCase();
    if (n.startsWith(q)) starts.push(p);
    else if (n.includes(q)) contains.push(p);
  });
  return [...starts, ...contains].slice(0, 8);
}

// ── Keepere (PL 26/27) ───────────────────────────────────────
const KEEPERS = [
  { name:'David Raya',              team:'ARS' },
  { name:'Kepa Arrizabalaga',       team:'ARS' },
  { name:'Emiliano Martínez',       team:'AVL' },
  { name:'Marco Bizot',             team:'AVL' },
  { name:'Đorđe Petrović',          team:'BOU' },
  { name:'Will Dennis',             team:'BOU' },
  { name:'Caoimhín Kelleher',       team:'BRE' },
  { name:'Hákon Valdimarsson',      team:'BRE' },
  { name:'Bart Verbruggen',         team:'BHA' },
  { name:'Jason Steele',            team:'BHA' },
  { name:'Robert Sánchez',          team:'CHE' },
  { name:'Filip Jörgensen',         team:'CHE' },
  { name:'Carl Rushworth',          team:'COV' },
  { name:'Ben Wilson',              team:'COV' },
  { name:'Dean Henderson',          team:'CRY' },
  { name:'Walter Benítez',          team:'CRY' },
  { name:'Jordan Pickford',         team:'EVE' },
  { name:'Mark Travers',            team:'EVE' },
  { name:'Bernd Leno',              team:'FUL' },
  { name:'Benjamin Lecomte',        team:'FUL' },
  { name:'Jack Butland',            team:'HUL' },
  { name:'Konstantinos Tzolakis',   team:'HUL' },
  { name:'Kjell Scherpen',          team:'IPS' },
  { name:'Christian Walton',        team:'IPS' },
  { name:'James Trafford',          team:'LEE' },
  { name:'Lucas Perri',             team:'LEE' },
  { name:'Alisson',                 team:'LIV' },
  { name:'Giorgi Mamardashvili',    team:'LIV' },
  { name:'Gianluigi Donnarumma',    team:'MCI' },
  { name:'Gerónimo Rulli',          team:'MCI' },
  { name:'Senne Lammens',           team:'MUN' },
  { name:'Karl Darlow',             team:'MUN' },
  { name:'Nick Pope',               team:'NEW' },
  { name:'Lukas Hornicek',          team:'NEW' },
  { name:'Matz Sels',               team:'NFO' },
  { name:'Angus Gunn',              team:'NFO' },
  { name:'Robin Roefs',             team:'SUN' },
  { name:'Anthony Patterson',       team:'SUN' },
  { name:'Guglielmo Vicario',       team:'TOT' },
  { name:'Martin Dubravka',         team:'TOT' },
];
function searchKeepers(q) {
  q = (q || '').trim().toLowerCase();
  const list = effectiveKeepers();
  if (!q) return list.slice(0, 8);
  const starts = [], contains = [];
  list.forEach(p => {
    const n = p.name.toLowerCase();
    if (n.startsWith(q)) starts.push(p);
    else if (n.includes(q)) contains.push(p);
  });
  return [...starts, ...contains].slice(0, 8);
}

// Utespillere + keepere samlet – for kåringer der en keeper også er et gyldig svar
// (kortpoeng, Årets spiller, første røde kort).
function searchAllPlayers(q) {
  q = (q || '').trim().toLowerCase();
  const all = [...effectivePlayers(), ...effectiveKeepers().map(k => ({ ...k, pos: k.pos || 'Keeper' }))];
  if (!q) return all.slice(0, 8);
  const starts = [], contains = [];
  all.forEach(p => {
    const n = p.name.toLowerCase();
    if (n.startsWith(q)) starts.push(p);
    else if (n.includes(q)) contains.push(p);
  });
  return [...starts, ...contains].slice(0, 8);
}
